### ISSUE TITLE
Variable list

### ISSUE THREAD

**Issue by utubun** [utubun/cub#1]
### Description

Give an overview of the data available with the description and explanation of all the variables found.

### Tasks

- [ ] List the table available for the analysis, add the description to every dataset. It must include the name of the table (possibly with the translation) and the domain it describes;
- [ ] For every listed dataset, list the variables it contains with concise translation, and explanation of the variable, plus the category of the variable (quantitative, qualitative);
- [ ] Are there any variables which falls into the same group i.e. connected, correlated? It's not about being precise but any reasonable guess.
